// -------------------------------------------------------------
// 
// File Name: E:\zgl\gen_7\slemi\emi_results\2024-05-23-08-02-25\SampleModel61741\Verilog_hdlsrc\sampleModel61741_pp_47_1_sub\cfblk130.v
// Created: 2024-05-23 08:43:24
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: cfblk130
// Source Path: sampleModel61741_pp_47_1_sub/Subsystem/cfblk130
// Hierarchy Level: 1
// Model version: 1.1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module cfblk130
          (clk,
           reset,
           enb,
           emi_74,
           Action_Port,
           emi_75);


  input   clk;
  input   reset;
  input   enb;
  input   [7:0] emi_74;  // uint8
  input   Action_Port;
  output  [7:0] emi_75;  // uint8


  wire [7:0] cfblk130_out1;  // uint8
  wire [7:0] cfblk130_out1_bypass;  // uint8
  reg [7:0] cfblk130_out1_last_value;  // uint8


  assign cfblk130_out1 = (emi_74 > 8'b00000000 ? 8'b00000001 :
              8'b00000000);



  always @(posedge clk or posedge reset)
    begin : emi_75_bypass_process
      if (reset == 1'b1) begin
        cfblk130_out1_last_value <= 8'b00000000;
      end
      else begin
        if (enb) begin
          cfblk130_out1_last_value <= cfblk130_out1_bypass;
        end
      end
    end



  assign cfblk130_out1_bypass = (Action_Port == 1'b0 ? cfblk130_out1_last_value :
              cfblk130_out1);



  assign emi_75 = cfblk130_out1_bypass;

endmodule  // cfblk130

