// -------------------------------------------------------------
// 
// File Name: E:\zgl\gen_7\slemi\emi_results\2024-05-23-08-02-25\SampleModel61741\Verilog_hdlsrc\sampleModel61741_pp_47_1_sub\cfblk154_block.v
// Created: 2024-05-23 08:43:24
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: cfblk154_block
// Source Path: sampleModel61741_pp_47_1_sub/Subsystem/cfblk154
// Hierarchy Level: 1
// Model version: 1.1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module cfblk154_block
          (clk,
           reset,
           enb,
           emi_360,
           Action_Port,
           emi_361);


  input   clk;
  input   reset;
  input   enb;
  input   [7:0] emi_360;  // uint8
  input   Action_Port;
  output  [7:0] emi_361;  // uint8


  wire [7:0] cfblk154_out1;  // uint8
  wire [7:0] cfblk154_out1_bypass;  // uint8
  reg [7:0] cfblk154_out1_last_value;  // uint8


  cfblk154 u_cfblk154 (.In1(emi_360),  // uint8
                       .Out1(cfblk154_out1)  // uint8
                       );

  always @(posedge clk or posedge reset)
    begin : emi_361_bypass_process
      if (reset == 1'b1) begin
        cfblk154_out1_last_value <= 8'b00000000;
      end
      else begin
        if (enb) begin
          cfblk154_out1_last_value <= cfblk154_out1_bypass;
        end
      end
    end



  assign cfblk154_out1_bypass = (Action_Port == 1'b0 ? cfblk154_out1_last_value :
              cfblk154_out1);



  assign emi_361 = cfblk154_out1_bypass;

endmodule  // cfblk154_block

