// -------------------------------------------------------------
// 
// File Name: E:\zgl\gen_7\slemi\emi_results\2024-05-23-08-02-25\SampleModel61741\Verilog_hdlsrc\sampleModel61741_pp_47_1_sub\cfblk82_block.v
// Created: 2024-05-23 08:43:24
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: cfblk82_block
// Source Path: sampleModel61741_pp_47_1_sub/Subsystem/cfblk82
// Hierarchy Level: 1
// Model version: 1.1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module cfblk82_block
          (clk,
           reset,
           enb,
           emi_336,
           Action_Port,
           emi_337);


  input   clk;
  input   reset;
  input   enb;
  input   [7:0] emi_336;  // uint8
  input   Action_Port;
  output  [7:0] emi_337;  // uint8


  wire [7:0] cfblk82_out1;  // uint8
  wire [7:0] cfblk82_out1_bypass;  // uint8
  reg [7:0] cfblk82_out1_last_value;  // uint8


  cfblk82 u_cfblk82 (.u(emi_336),  // uint8
                     .y(cfblk82_out1)  // uint8
                     );

  always @(posedge clk or posedge reset)
    begin : emi_337_bypass_process
      if (reset == 1'b1) begin
        cfblk82_out1_last_value <= 8'b00000000;
      end
      else begin
        if (enb) begin
          cfblk82_out1_last_value <= cfblk82_out1_bypass;
        end
      end
    end



  assign cfblk82_out1_bypass = (Action_Port == 1'b0 ? cfblk82_out1_last_value :
              cfblk82_out1);



  assign emi_337 = cfblk82_out1_bypass;

endmodule  // cfblk82_block

