// -------------------------------------------------------------
// 
// File Name: E:\zgl\gen_2\slemi\emi_results\2024-05-23-05-35-36\SampleModel71194\Verilog_hdlsrc\sampleModel71194_pp_7_1_sub\cfblk135.v
// Created: 2024-05-23 05:41:31
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: cfblk135
// Source Path: sampleModel71194_pp_7_1_sub/Subsystem/cfblk135
// Hierarchy Level: 1
// Model version: 1.1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module cfblk135
          (clk,
           reset,
           enb,
           emi_59,
           Action_Port,
           emi_60);


  input   clk;
  input   reset;
  input   enb;
  input   [7:0] emi_59;  // uint8
  input   Action_Port;
  output  [15:0] emi_60;  // ufix16_En7


  wire [15:0] cfblk135_out1;  // ufix16_En7
  wire [15:0] cfblk135_out1_bypass;  // ufix16_En7
  reg [15:0] cfblk135_out1_last_value;  // ufix16_En7


  assign cfblk135_out1 = {1'b0, {emi_59, 7'b0000000}};



  always @(posedge clk or posedge reset)
    begin : emi_60_bypass_process
      if (reset == 1'b1) begin
        cfblk135_out1_last_value <= 16'b0000000000000000;
      end
      else begin
        if (enb) begin
          cfblk135_out1_last_value <= cfblk135_out1_bypass;
        end
      end
    end



  assign cfblk135_out1_bypass = (Action_Port == 1'b0 ? cfblk135_out1_last_value :
              cfblk135_out1);



  assign emi_60 = cfblk135_out1_bypass;

endmodule  // cfblk135

