// -------------------------------------------------------------
// 
// File Name: E:\zgl\gen_2\slemi\emi_results\2024-05-23-05-35-36\SampleModel71194\Verilog_hdlsrc\sampleModel71194_pp_7_1_sub\cfblk127.v
// Created: 2024-05-23 05:41:31
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: cfblk127
// Source Path: sampleModel71194_pp_7_1_sub/Subsystem/cfblk127
// Hierarchy Level: 1
// Model version: 1.1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module cfblk127
          (clk,
           reset,
           enb,
           emi_25,
           Action_Port,
           emi_26,
           emi_27);


  input   clk;
  input   reset;
  input   enb;
  input   [7:0] emi_25;  // uint8
  input   Action_Port;
  output  [7:0] emi_26;  // uint8
  output  [7:0] emi_27;  // uint8


  wire [7:0] cfblk127_out1;  // uint8
  wire [7:0] cfblk127_out2;  // uint8
  wire [7:0] cfblk127_out1_bypass;  // uint8
  reg [7:0] cfblk127_out1_last_value;  // uint8
  wire [7:0] cfblk127_out2_bypass;  // uint8
  reg [7:0] cfblk127_out2_last_value;  // uint8


  assign cfblk127_out1 = emi_25;
  assign cfblk127_out2 = 8'b00000000;



  always @(posedge clk or posedge reset)
    begin : emi_26_bypass_process
      if (reset == 1'b1) begin
        cfblk127_out1_last_value <= 8'b00000000;
      end
      else begin
        if (enb) begin
          cfblk127_out1_last_value <= cfblk127_out1_bypass;
        end
      end
    end



  assign cfblk127_out1_bypass = (Action_Port == 1'b0 ? cfblk127_out1_last_value :
              cfblk127_out1);



  assign emi_26 = cfblk127_out1_bypass;

  always @(posedge clk or posedge reset)
    begin : emi_27_bypass_process
      if (reset == 1'b1) begin
        cfblk127_out2_last_value <= 8'b00000000;
      end
      else begin
        if (enb) begin
          cfblk127_out2_last_value <= cfblk127_out2_bypass;
        end
      end
    end



  assign cfblk127_out2_bypass = (Action_Port == 1'b0 ? cfblk127_out2_last_value :
              cfblk127_out2);



  assign emi_27 = cfblk127_out2_bypass;

endmodule  // cfblk127

