// -------------------------------------------------------------
// 
// File Name: E:\zgl\gen_2\slemi\emi_results\2024-05-23-05-35-36\SampleModel71194\Verilog_hdlsrc\sampleModel71194_pp_7_1_sub\cfblk93.v
// Created: 2024-05-23 05:41:31
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: cfblk93
// Source Path: sampleModel71194_pp_7_1_sub/Subsystem/cfblk93
// Hierarchy Level: 1
// Model version: 1.1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module cfblk93
          (clk,
           reset,
           enb,
           emi_319,
           Action_Port,
           emi_320,
           emi_321);


  input   clk;
  input   reset;
  input   enb;
  input   [7:0] emi_319;  // uint8
  input   Action_Port;
  output  [7:0] emi_320;  // uint8
  output  [7:0] emi_321;  // uint8


  wire [7:0] cfblk93_out1;  // uint8
  wire [7:0] cfblk93_out2;  // uint8
  wire [7:0] cfblk93_out1_bypass;  // uint8
  reg [7:0] cfblk93_out1_last_value;  // uint8
  wire [7:0] cfblk93_out2_bypass;  // uint8
  reg [7:0] cfblk93_out2_last_value;  // uint8


  assign cfblk93_out1 = emi_319;
  assign cfblk93_out2 = 8'b00000000;



  always @(posedge clk or posedge reset)
    begin : emi_320_bypass_process
      if (reset == 1'b1) begin
        cfblk93_out1_last_value <= 8'b00000000;
      end
      else begin
        if (enb) begin
          cfblk93_out1_last_value <= cfblk93_out1_bypass;
        end
      end
    end



  assign cfblk93_out1_bypass = (Action_Port == 1'b0 ? cfblk93_out1_last_value :
              cfblk93_out1);



  assign emi_320 = cfblk93_out1_bypass;

  always @(posedge clk or posedge reset)
    begin : emi_321_bypass_process
      if (reset == 1'b1) begin
        cfblk93_out2_last_value <= 8'b00000000;
      end
      else begin
        if (enb) begin
          cfblk93_out2_last_value <= cfblk93_out2_bypass;
        end
      end
    end



  assign cfblk93_out2_bypass = (Action_Port == 1'b0 ? cfblk93_out2_last_value :
              cfblk93_out2);



  assign emi_321 = cfblk93_out2_bypass;

endmodule  // cfblk93

