// -------------------------------------------------------------
// 
// File Name: E:\zgl\gen_2\slemi\emi_results\2024-05-23-05-35-36\SampleModel71194\Verilog_hdlsrc\sampleModel71194_pp_7_1_sub\cfblk6.v
// Created: 2024-05-23 05:41:31
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: cfblk6
// Source Path: sampleModel71194_pp_7_1_sub/Subsystem/cfblk6
// Hierarchy Level: 1
// Model version: 1.1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module cfblk6
          (clk,
           reset,
           enb,
           emi_287,
           Action_Port,
           emi_288);


  input   clk;
  input   reset;
  input   enb;
  input   emi_287;
  input   Action_Port;
  output  emi_288;


  wire bitMask_for_cfblk6;
  wire cfblk6_out1;
  wire cfblk6_out1_bypass;
  reg  cfblk6_out1_last_value;


  assign bitMask_for_cfblk6 = 1'b1;



  assign cfblk6_out1 = emi_287 & bitMask_for_cfblk6;



  always @(posedge clk or posedge reset)
    begin : emi_288_bypass_process
      if (reset == 1'b1) begin
        cfblk6_out1_last_value <= 1'b0;
      end
      else begin
        if (enb) begin
          cfblk6_out1_last_value <= cfblk6_out1_bypass;
        end
      end
    end



  assign cfblk6_out1_bypass = (Action_Port == 1'b0 ? cfblk6_out1_last_value :
              cfblk6_out1);



  assign emi_288 = cfblk6_out1_bypass;

endmodule  // cfblk6

