// -------------------------------------------------------------
// 
// File Name: E:\zgl\gen_3\slemi\emi_results\2024-05-22-23-05-26\SampleModel66206\Verilog_hdlsrc\sampleModel66206_pp_7_1_sub\cfblk70.v
// Created: 2024-05-22 23:12:28
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: cfblk70
// Source Path: sampleModel66206_pp_7_1_sub/Subsystem/cfblk70
// Hierarchy Level: 1
// Model version: 1.1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module cfblk70
          (clk,
           reset,
           enb,
           emi_243,
           Action_Port,
           emi_244,
           emi_245);


  input   clk;
  input   reset;
  input   enb;
  input   [7:0] emi_243;  // uint8
  input   Action_Port;
  output  [7:0] emi_244;  // uint8
  output  [7:0] emi_245;  // uint8


  wire [7:0] cfblk70_out1;  // uint8
  wire [7:0] cfblk70_out2;  // uint8
  wire [7:0] cfblk70_out1_bypass;  // uint8
  reg [7:0] cfblk70_out1_last_value;  // uint8
  wire [7:0] cfblk70_out2_bypass;  // uint8
  reg [7:0] cfblk70_out2_last_value;  // uint8


  assign cfblk70_out1 = emi_243;
  assign cfblk70_out2 = 8'b00000000;



  always @(posedge clk or posedge reset)
    begin : emi_244_bypass_process
      if (reset == 1'b1) begin
        cfblk70_out1_last_value <= 8'b00000000;
      end
      else begin
        if (enb) begin
          cfblk70_out1_last_value <= cfblk70_out1_bypass;
        end
      end
    end



  assign cfblk70_out1_bypass = (Action_Port == 1'b0 ? cfblk70_out1_last_value :
              cfblk70_out1);



  assign emi_244 = cfblk70_out1_bypass;

  always @(posedge clk or posedge reset)
    begin : emi_245_bypass_process
      if (reset == 1'b1) begin
        cfblk70_out2_last_value <= 8'b00000000;
      end
      else begin
        if (enb) begin
          cfblk70_out2_last_value <= cfblk70_out2_bypass;
        end
      end
    end



  assign cfblk70_out2_bypass = (Action_Port == 1'b0 ? cfblk70_out2_last_value :
              cfblk70_out2);



  assign emi_245 = cfblk70_out2_bypass;

endmodule  // cfblk70

