// -------------------------------------------------------------
// 
// File Name: E:\zgl\gen_3\slemi\emi_results\2024-05-22-23-05-26\SampleModel66206\Verilog_hdlsrc\sampleModel66206_pp_7_1_sub\cfblk5_block.v
// Created: 2024-05-22 23:12:28
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: cfblk5_block
// Source Path: sampleModel66206_pp_7_1_sub/Subsystem/cfblk5
// Hierarchy Level: 1
// Model version: 1.1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module cfblk5_block
          (clk,
           reset,
           enb,
           emi_202,
           Action_Port,
           emi_203);


  input   clk;
  input   reset;
  input   enb;
  input   [15:0] emi_202;  // ufix16_En7
  input   Action_Port;
  output  [7:0] emi_203;  // uint8


  wire [7:0] cfblk5_out1;  // uint8
  wire [7:0] cfblk5_out1_bypass;  // uint8
  reg [7:0] cfblk5_out1_last_value;  // uint8


  cfblk5 u_cfblk5 (.clk(clk),
                   .reset(reset),
                   .enb(enb),
                   .U(emi_202),  // ufix16_En7
                   .Action_Port_out2(Action_Port),
                   .Y(cfblk5_out1)  // uint8
                   );

  always @(posedge clk or posedge reset)
    begin : emi_203_bypass_process
      if (reset == 1'b1) begin
        cfblk5_out1_last_value <= 8'b00000000;
      end
      else begin
        if (enb) begin
          cfblk5_out1_last_value <= cfblk5_out1_bypass;
        end
      end
    end



  assign cfblk5_out1_bypass = (Action_Port == 1'b0 ? cfblk5_out1_last_value :
              cfblk5_out1);



  assign emi_203 = cfblk5_out1_bypass;

endmodule  // cfblk5_block

