// -------------------------------------------------------------
// 
// File Name: E:\zgl\gen_3\slemi\emi_results\2024-05-22-23-05-26\SampleModel66206\Verilog_hdlsrc\sampleModel66206_pp_7_1_sub\cfblk54.v
// Created: 2024-05-22 23:12:28
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: cfblk54
// Source Path: sampleModel66206_pp_7_1_sub/Subsystem/cfblk54
// Hierarchy Level: 1
// Model version: 1.1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module cfblk54
          (clk,
           reset,
           enb,
           emi_226,
           Action_Port,
           emi_227,
           emi_228);


  input   clk;
  input   reset;
  input   enb;
  input   [7:0] emi_226;  // uint8
  input   Action_Port;
  output  [7:0] emi_227;  // uint8
  output  [7:0] emi_228;  // uint8


  wire [7:0] cfblk54_out1;  // uint8
  wire [7:0] cfblk54_out2;  // uint8
  wire [7:0] cfblk54_out1_bypass;  // uint8
  reg [7:0] cfblk54_out1_last_value;  // uint8
  wire [7:0] cfblk54_out2_bypass;  // uint8
  reg [7:0] cfblk54_out2_last_value;  // uint8


  assign cfblk54_out1 = emi_226;
  assign cfblk54_out2 = 8'b00000000;



  always @(posedge clk or posedge reset)
    begin : emi_227_bypass_process
      if (reset == 1'b1) begin
        cfblk54_out1_last_value <= 8'b00000000;
      end
      else begin
        if (enb) begin
          cfblk54_out1_last_value <= cfblk54_out1_bypass;
        end
      end
    end



  assign cfblk54_out1_bypass = (Action_Port == 1'b0 ? cfblk54_out1_last_value :
              cfblk54_out1);



  assign emi_227 = cfblk54_out1_bypass;

  always @(posedge clk or posedge reset)
    begin : emi_228_bypass_process
      if (reset == 1'b1) begin
        cfblk54_out2_last_value <= 8'b00000000;
      end
      else begin
        if (enb) begin
          cfblk54_out2_last_value <= cfblk54_out2_bypass;
        end
      end
    end



  assign cfblk54_out2_bypass = (Action_Port == 1'b0 ? cfblk54_out2_last_value :
              cfblk54_out2);



  assign emi_228 = cfblk54_out2_bypass;

endmodule  // cfblk54

