// -------------------------------------------------------------
// 
// File Name: E:\zgl\gen_3\slemi\emi_results\2024-05-22-23-05-26\SampleModel66206\Verilog_hdlsrc\sampleModel66206_pp_7_1_sub\Nonpositive_block1.v
// Created: 2024-05-22 23:12:28
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Nonpositive_block1
// Source Path: sampleModel66206_pp_7_1_sub/Subsystem/cfblk5/cfblk5/Nonpositive
// Hierarchy Level: 3
// Model version: 1.1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Nonpositive_block1
          (u,
           y);


  input   [15:0] u;  // ufix16_En7
  output  y;


  wire [15:0] Constant_out1;  // ufix16_En7
  wire Compare_relop1;


  assign Constant_out1 = 16'b0000000000000000;



  assign Compare_relop1 = u <= Constant_out1;



  assign y = Compare_relop1;

endmodule  // Nonpositive_block1

