// -------------------------------------------------------------
// 
// File Name: E:\zgl\gen_6\slemi\emi_results\2024-05-23-07-46-43\SampleModel61753\Verilog_hdlsrc\sampleModel61753_pp_45_1_sub\cfblk159_block.v
// Created: 2024-05-23 08:17:51
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: cfblk159_block
// Source Path: sampleModel61753_pp_45_1_sub/Subsystem/cfblk159
// Hierarchy Level: 1
// Model version: 1.1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module cfblk159_block
          (clk,
           reset,
           enb,
           emi_156,
           Action_Port,
           emi_157);


  input   clk;
  input   reset;
  input   enb;
  input   [7:0] emi_156;  // uint8
  input   Action_Port;
  output  [7:0] emi_157;  // uint8


  wire [7:0] cfblk159_out1;  // uint8
  wire [7:0] cfblk159_out1_bypass;  // uint8
  reg [7:0] cfblk159_out1_last_value;  // uint8


  cfblk159 u_cfblk159 (.In1(emi_156),  // uint8
                       .Out1(cfblk159_out1)  // uint8
                       );

  always @(posedge clk or posedge reset)
    begin : emi_157_bypass_process
      if (reset == 1'b1) begin
        cfblk159_out1_last_value <= 8'b00000000;
      end
      else begin
        if (enb) begin
          cfblk159_out1_last_value <= cfblk159_out1_bypass;
        end
      end
    end



  assign cfblk159_out1_bypass = (Action_Port == 1'b0 ? cfblk159_out1_last_value :
              cfblk159_out1);



  assign emi_157 = cfblk159_out1_bypass;

endmodule  // cfblk159_block

