// -------------------------------------------------------------
// 
// File Name: E:\zgl\gen_6\slemi\emi_results\2024-05-23-07-46-43\SampleModel61753\Verilog_hdlsrc\sampleModel61753_pp_45_1_sub\cfblk172.v
// Created: 2024-05-23 08:17:51
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: cfblk172
// Source Path: sampleModel61753_pp_45_1_sub/Subsystem/cfblk172
// Hierarchy Level: 1
// Model version: 1.1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module cfblk172
          (clk,
           reset,
           enb,
           emi_66,
           Action_Port,
           emi_67);


  input   clk;
  input   reset;
  input   enb;
  input   [7:0] emi_66;  // uint8
  input   Action_Port;
  output  [7:0] emi_67;  // uint8


  wire enb_gated;
  reg [7:0] cfblk172_reg [0:1];  // ufix8 [2]
  wire [7:0] cfblk172_reg_next [0:1];  // ufix8 [2]
  wire [7:0] cfblk172_out1;  // uint8
  wire [7:0] cfblk172_out1_1;  // uint8
  reg [7:0] cfblk172_out1_last_value;  // uint8
  reg signed [31:0] cfblk172_t_0_0;  // int32
  reg signed [31:0] cfblk172_t_1;  // int32


  assign enb_gated = Action_Port && enb;

  always @(posedge clk or posedge reset)
    begin : cfblk172_1_process
      if (reset == 1'b1) begin
        for(cfblk172_t_1 = 32'sd0; cfblk172_t_1 <= 32'sd1; cfblk172_t_1 = cfblk172_t_1 + 32'sd1) begin
          cfblk172_reg[cfblk172_t_1] <= 8'b00000000;
        end
      end
      else begin
        if (enb_gated) begin
          for(cfblk172_t_0_0 = 32'sd0; cfblk172_t_0_0 <= 32'sd1; cfblk172_t_0_0 = cfblk172_t_0_0 + 32'sd1) begin
            cfblk172_reg[cfblk172_t_0_0] <= cfblk172_reg_next[cfblk172_t_0_0];
          end
        end
      end
    end

  assign cfblk172_out1 = cfblk172_reg[1];
  assign cfblk172_reg_next[0] = emi_66;
  assign cfblk172_reg_next[1] = cfblk172_reg[0];



  always @(posedge clk or posedge reset)
    begin : out0_bypass_process
      if (reset == 1'b1) begin
        cfblk172_out1_last_value <= 8'b00000000;
      end
      else begin
        if (enb_gated) begin
          cfblk172_out1_last_value <= cfblk172_out1_1;
        end
      end
    end



  assign cfblk172_out1_1 = (Action_Port == 1'b0 ? cfblk172_out1_last_value :
              cfblk172_out1);



  assign emi_67 = cfblk172_out1_1;

endmodule  // cfblk172

