// -------------------------------------------------------------
// 
// File Name: E:\zgl\gen_10\slemi\emi_results\2024-05-23-02-20-21\SampleModel61556\Verilog_hdlsrc\sampleModel61556_pp_34_1_sub\cfblk10.v
// Created: 2024-05-23 02:55:47
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: cfblk10
// Source Path: sampleModel61556_pp_34_1_sub/Subsystem/cfblk10
// Hierarchy Level: 1
// Model version: 1.1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module cfblk10
          (clk,
           reset,
           enb,
           emi_1,
           Action_Port,
           emi_2);


  input   clk;
  input   reset;
  input   enb;
  input   [7:0] emi_1;  // uint8
  input   Action_Port;
  output  [7:0] emi_2;  // uint8


  wire [7:0] dtc_out;  // ufix8
  wire [7:0] cfblk10_out1;  // uint8
  wire [7:0] cfblk10_out1_bypass;  // uint8
  reg [7:0] cfblk10_out1_last_value;  // uint8


  assign dtc_out = emi_1;



  assign cfblk10_out1 = dtc_out;



  always @(posedge clk or posedge reset)
    begin : emi_2_bypass_process
      if (reset == 1'b1) begin
        cfblk10_out1_last_value <= 8'b00000000;
      end
      else begin
        if (enb) begin
          cfblk10_out1_last_value <= cfblk10_out1_bypass;
        end
      end
    end



  assign cfblk10_out1_bypass = (Action_Port == 1'b0 ? cfblk10_out1_last_value :
              cfblk10_out1);



  assign emi_2 = cfblk10_out1_bypass;

endmodule  // cfblk10

