// -------------------------------------------------------------
// 
// File Name: E:\zgl\gen_10\slemi\emi_results\2024-05-23-02-20-21\SampleModel61556\Verilog_hdlsrc\sampleModel61556_pp_34_1_sub\cfblk49.v
// Created: 2024-05-23 02:55:47
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: cfblk49
// Source Path: sampleModel61556_pp_34_1_sub/Subsystem/cfblk49
// Hierarchy Level: 1
// Model version: 1.1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module cfblk49
          (clk,
           reset,
           enb,
           emi_219,
           Action_Port,
           emi_220,
           emi_221);


  input   clk;
  input   reset;
  input   enb;
  input   [7:0] emi_219;  // uint8
  input   Action_Port;
  output  [7:0] emi_220;  // uint8
  output  [7:0] emi_221;  // uint8


  wire [7:0] cfblk49_out1;  // uint8
  wire [7:0] cfblk49_out2;  // uint8
  wire [7:0] cfblk49_out1_bypass;  // uint8
  reg [7:0] cfblk49_out1_last_value;  // uint8
  wire [7:0] cfblk49_out2_bypass;  // uint8
  reg [7:0] cfblk49_out2_last_value;  // uint8


  assign cfblk49_out1 = emi_219;
  assign cfblk49_out2 = 8'b00000000;



  always @(posedge clk or posedge reset)
    begin : emi_220_bypass_process
      if (reset == 1'b1) begin
        cfblk49_out1_last_value <= 8'b00000000;
      end
      else begin
        if (enb) begin
          cfblk49_out1_last_value <= cfblk49_out1_bypass;
        end
      end
    end



  assign cfblk49_out1_bypass = (Action_Port == 1'b0 ? cfblk49_out1_last_value :
              cfblk49_out1);



  assign emi_220 = cfblk49_out1_bypass;

  always @(posedge clk or posedge reset)
    begin : emi_221_bypass_process
      if (reset == 1'b1) begin
        cfblk49_out2_last_value <= 8'b00000000;
      end
      else begin
        if (enb) begin
          cfblk49_out2_last_value <= cfblk49_out2_bypass;
        end
      end
    end



  assign cfblk49_out2_bypass = (Action_Port == 1'b0 ? cfblk49_out2_last_value :
              cfblk49_out2);



  assign emi_221 = cfblk49_out2_bypass;

endmodule  // cfblk49

