// -------------------------------------------------------------
// 
// File Name: E:\zgl\gen_10\slemi\emi_results\2024-05-23-02-20-21\SampleModel61556\Verilog_hdlsrc\sampleModel61556_pp_34_1_sub\cfblk96.v
// Created: 2024-05-23 02:55:47
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: cfblk96
// Source Path: sampleModel61556_pp_34_1_sub/Subsystem/cfblk96
// Hierarchy Level: 1
// Model version: 1.1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module cfblk96
          (clk,
           reset,
           enb,
           emi_309,
           Action_Port,
           emi_310);


  input   clk;
  input   reset;
  input   enb;
  input   [7:0] emi_309;  // uint8
  input   Action_Port;
  output  [7:0] emi_310;  // uint8


  wire [7:0] cfblk96_out1_bypass;  // uint8
  reg [7:0] cfblk96_out1_last_value;  // uint8


  always @(posedge clk or posedge reset)
    begin : emi_310_bypass_process
      if (reset == 1'b1) begin
        cfblk96_out1_last_value <= 8'b00000000;
      end
      else begin
        if (enb) begin
          cfblk96_out1_last_value <= cfblk96_out1_bypass;
        end
      end
    end



  assign cfblk96_out1_bypass = (Action_Port == 1'b0 ? cfblk96_out1_last_value :
              emi_309);



  assign emi_310 = cfblk96_out1_bypass;

endmodule  // cfblk96

