// -------------------------------------------------------------
// 
// File Name: E:\zgl\gen_10\slemi\emi_results\2024-05-23-02-20-21\SampleModel61556\Verilog_hdlsrc\sampleModel61556_pp_34_1_sub\cfblk4_block.v
// Created: 2024-05-23 02:55:47
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: cfblk4_block
// Source Path: sampleModel61556_pp_34_1_sub/Subsystem/cfblk4
// Hierarchy Level: 1
// Model version: 1.1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module cfblk4_block
          (clk,
           reset,
           enb,
           emi_195,
           Action_Port,
           emi_196);


  input   clk;
  input   reset;
  input   enb;
  input   [7:0] emi_195;  // uint8
  input   Action_Port;
  output  [7:0] emi_196;  // uint8


  wire [7:0] cfblk4_out1;  // uint8
  wire [7:0] cfblk4_out1_bypass;  // uint8
  reg [7:0] cfblk4_out1_last_value;  // uint8


  cfblk4 u_cfblk4 (.clk(clk),
                   .reset(reset),
                   .enb(enb),
                   .U(emi_195),  // uint8
                   .Action_Port_out2(Action_Port),
                   .Y(cfblk4_out1)  // uint8
                   );

  always @(posedge clk or posedge reset)
    begin : emi_196_bypass_process
      if (reset == 1'b1) begin
        cfblk4_out1_last_value <= 8'b00000000;
      end
      else begin
        if (enb) begin
          cfblk4_out1_last_value <= cfblk4_out1_bypass;
        end
      end
    end



  assign cfblk4_out1_bypass = (Action_Port == 1'b0 ? cfblk4_out1_last_value :
              cfblk4_out1);



  assign emi_196 = cfblk4_out1_bypass;

endmodule  // cfblk4_block

