// -------------------------------------------------------------
// 
// File Name: E:\zgl\gen_9\slemi\emi_results\2024-05-23-02-49-52\SampleModel61706\Verilog_hdlsrc\sampleModel61706_pp_36_1_sub\cfblk10.v
// Created: 2024-05-23 03:39:09
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: cfblk10
// Source Path: sampleModel61706_pp_36_1_sub/Subsystem/cfblk10
// Hierarchy Level: 1
// Model version: 1.1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module cfblk10
          (clk,
           reset,
           enb,
           emi_1,
           Action_Port,
           emi_2);


  input   clk;
  input   reset;
  input   enb;
  input   [7:0] emi_1;  // uint8
  input   Action_Port;
  output  [15:0] emi_2;  // ufix16_En7


  wire [15:0] cfblk10_out1;  // ufix16_En7
  wire [15:0] cfblk10_out1_bypass;  // ufix16_En7
  reg [15:0] cfblk10_out1_last_value;  // ufix16_En7


  assign cfblk10_out1 = {1'b0, {emi_1, 7'b0000000}};



  always @(posedge clk or posedge reset)
    begin : emi_2_bypass_process
      if (reset == 1'b1) begin
        cfblk10_out1_last_value <= 16'b0000000000000000;
      end
      else begin
        if (enb) begin
          cfblk10_out1_last_value <= cfblk10_out1_bypass;
        end
      end
    end



  assign cfblk10_out1_bypass = (Action_Port == 1'b0 ? cfblk10_out1_last_value :
              cfblk10_out1);



  assign emi_2 = cfblk10_out1_bypass;

endmodule  // cfblk10

