// -------------------------------------------------------------
// 
// File Name: E:\zgl\gen_9\slemi\emi_results\2024-05-23-02-49-52\SampleModel61706\Verilog_hdlsrc\sampleModel61706_pp_36_1_sub\cfblk218.v
// Created: 2024-05-23 03:39:09
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: cfblk218
// Source Path: sampleModel61706_pp_36_1_sub/Subsystem/cfblk218
// Hierarchy Level: 1
// Model version: 1.1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module cfblk218
          (clk,
           reset,
           enb,
           emi_139,
           Action_Port,
           emi_140);


  input   clk;
  input   reset;
  input   enb;
  input   [7:0] emi_139;  // uint8
  input   Action_Port;
  output  [7:0] emi_140;  // uint8


  wire [7:0] cfblk218_out1_bypass;  // uint8
  reg [7:0] cfblk218_out1_last_value;  // uint8


  always @(posedge clk or posedge reset)
    begin : emi_140_bypass_process
      if (reset == 1'b1) begin
        cfblk218_out1_last_value <= 8'b00000000;
      end
      else begin
        if (enb) begin
          cfblk218_out1_last_value <= cfblk218_out1_bypass;
        end
      end
    end



  assign cfblk218_out1_bypass = (Action_Port == 1'b0 ? cfblk218_out1_last_value :
              emi_139);



  assign emi_140 = cfblk218_out1_bypass;

endmodule  // cfblk218

