// -------------------------------------------------------------
// 
// File Name: E:\zgl\gen_9\slemi\emi_results\2024-05-23-02-49-52\SampleModel61706\Verilog_hdlsrc\sampleModel61706_pp_36_1_sub\cfblk74.v
// Created: 2024-05-23 03:39:10
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: cfblk74
// Source Path: sampleModel61706_pp_36_1_sub/Subsystem/cfblk74
// Hierarchy Level: 1
// Model version: 1.1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module cfblk74
          (clk,
           reset,
           enb,
           emi_243,
           Action_Port,
           emi_244);


  input   clk;
  input   reset;
  input   enb;
  input   [15:0] emi_243;  // ufix16_En7
  input   Action_Port;
  output  [15:0] emi_244;  // ufix16_En7


  wire [15:0] cfblk74_out1_bypass;  // ufix16_En7
  reg [15:0] cfblk74_out1_last_value;  // ufix16_En7


  always @(posedge clk or posedge reset)
    begin : emi_244_bypass_process
      if (reset == 1'b1) begin
        cfblk74_out1_last_value <= 16'b0000000000000000;
      end
      else begin
        if (enb) begin
          cfblk74_out1_last_value <= cfblk74_out1_bypass;
        end
      end
    end



  assign cfblk74_out1_bypass = (Action_Port == 1'b0 ? cfblk74_out1_last_value :
              emi_243);



  assign emi_244 = cfblk74_out1_bypass;

endmodule  // cfblk74

