// -------------------------------------------------------------
// 
// File Name: E:\zgl\gen_9\slemi\emi_results\2024-05-23-02-49-52\SampleModel61706\Verilog_hdlsrc\sampleModel61706_pp_36_1_sub\cfblk179.v
// Created: 2024-05-23 03:39:09
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: cfblk179
// Source Path: sampleModel61706_pp_36_1_sub/Subsystem/cfblk179
// Hierarchy Level: 1
// Model version: 1.1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module cfblk179
          (clk,
           reset,
           enb,
           emi_130,
           Action_Port,
           emi_131,
           emi_132);


  input   clk;
  input   reset;
  input   enb;
  input   [7:0] emi_130;  // uint8
  input   Action_Port;
  output  [7:0] emi_131;  // uint8
  output  [7:0] emi_132;  // uint8


  wire [7:0] cfblk179_out1;  // uint8
  wire [7:0] cfblk179_out2;  // uint8
  wire [7:0] cfblk179_out1_bypass;  // uint8
  reg [7:0] cfblk179_out1_last_value;  // uint8
  wire [7:0] cfblk179_out2_bypass;  // uint8
  reg [7:0] cfblk179_out2_last_value;  // uint8


  assign cfblk179_out1 = emi_130;
  assign cfblk179_out2 = 8'b00000000;



  always @(posedge clk or posedge reset)
    begin : emi_131_bypass_process
      if (reset == 1'b1) begin
        cfblk179_out1_last_value <= 8'b00000000;
      end
      else begin
        if (enb) begin
          cfblk179_out1_last_value <= cfblk179_out1_bypass;
        end
      end
    end



  assign cfblk179_out1_bypass = (Action_Port == 1'b0 ? cfblk179_out1_last_value :
              cfblk179_out1);



  assign emi_131 = cfblk179_out1_bypass;

  always @(posedge clk or posedge reset)
    begin : emi_132_bypass_process
      if (reset == 1'b1) begin
        cfblk179_out2_last_value <= 8'b00000000;
      end
      else begin
        if (enb) begin
          cfblk179_out2_last_value <= cfblk179_out2_bypass;
        end
      end
    end



  assign cfblk179_out2_bypass = (Action_Port == 1'b0 ? cfblk179_out2_last_value :
              cfblk179_out2);



  assign emi_132 = cfblk179_out2_bypass;

endmodule  // cfblk179

