// -------------------------------------------------------------
// 
// File Name: E:\zgl\gen_9\slemi\emi_results\2024-05-23-02-49-52\SampleModel61706\Verilog_hdlsrc\sampleModel61706_pp_36_1_sub\cfblk4.v
// Created: 2024-05-23 03:39:09
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: cfblk4
// Source Path: sampleModel61706_pp_36_1_sub/Subsystem/cfblk4
// Hierarchy Level: 1
// Model version: 1.1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module cfblk4
          (u,
           y);


  input   [63:0] u;  // double
  output  [7:0] y;  // uint8


  real u_double;  // double
  real Constant_out1;  // double
  wire Compare_relop1;
  wire [7:0] Compare_relop1_dtc;  // uint8


  always @* u_double = $bitstoreal(u);

  initial Constant_out1 = 0.0;



  assign Compare_relop1 = u_double <= Constant_out1;



  assign Compare_relop1_dtc = {7'b0, Compare_relop1};



  assign y = Compare_relop1_dtc;

endmodule  // cfblk4

