// -------------------------------------------------------------
// 
// File Name: E:\zgl\gen_6\slemi\emi_results\2024-05-22-21-58-05\SampleModel61442\Verilog_hdlsrc\sampleModel61442_pp_12_1_sub\cfblk144.v
// Created: 2024-05-22 22:32:07
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: cfblk144
// Source Path: sampleModel61442_pp_12_1_sub/Subsystem/cfblk144
// Hierarchy Level: 1
// Model version: 1.1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module cfblk144
          (clk,
           reset,
           enb,
           emi_115,
           Action_Port,
           emi_116);


  input   clk;
  input   reset;
  input   enb;
  input   [7:0] emi_115;  // uint8
  input   Action_Port;
  output  [7:0] emi_116;  // uint8


  wire [7:0] cfblk144_out1_bypass;  // uint8
  reg [7:0] cfblk144_out1_last_value;  // uint8


  always @(posedge clk or posedge reset)
    begin : emi_116_bypass_process
      if (reset == 1'b1) begin
        cfblk144_out1_last_value <= 8'b00000000;
      end
      else begin
        if (enb) begin
          cfblk144_out1_last_value <= cfblk144_out1_bypass;
        end
      end
    end



  assign cfblk144_out1_bypass = (Action_Port == 1'b0 ? cfblk144_out1_last_value :
              emi_115);



  assign emi_116 = cfblk144_out1_bypass;

endmodule  // cfblk144

