// -------------------------------------------------------------
// 
// File Name: E:\zgl\gen_2\slemi\emi_results\2024-05-23-05-22-55\SampleModel71194\Verilog_hdlsrc\sampleModel71194_pp_7_1_sub\cfblk138.v
// Created: 2024-05-23 05:31:58
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: cfblk138
// Source Path: sampleModel71194_pp_7_1_sub/Subsystem/cfblk138
// Hierarchy Level: 1
// Model version: 1.1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module cfblk138
          (clk,
           reset,
           enb,
           emi_41,
           Action_Port,
           emi_42);


  input   clk;
  input   reset;
  input   enb;
  input   [7:0] emi_41;  // uint8
  input   Action_Port;
  output  [7:0] emi_42;  // uint8


  wire [7:0] dtc_out;  // ufix8
  wire [7:0] cfblk138_out1;  // uint8
  wire [7:0] cfblk138_out1_bypass;  // uint8
  reg [7:0] cfblk138_out1_last_value;  // uint8


  assign dtc_out = emi_41;



  assign cfblk138_out1 = dtc_out;



  always @(posedge clk or posedge reset)
    begin : emi_42_bypass_process
      if (reset == 1'b1) begin
        cfblk138_out1_last_value <= 8'b00000000;
      end
      else begin
        if (enb) begin
          cfblk138_out1_last_value <= cfblk138_out1_bypass;
        end
      end
    end



  assign cfblk138_out1_bypass = (Action_Port == 1'b0 ? cfblk138_out1_last_value :
              cfblk138_out1);



  assign emi_42 = cfblk138_out1_bypass;

endmodule  // cfblk138

