// -------------------------------------------------------------
// 
// File Name: E:\zgl\gen_2\slemi\emi_results\2024-05-23-05-22-55\SampleModel71194\Verilog_hdlsrc\sampleModel71194_pp_7_1_sub\cfblk58.v
// Created: 2024-05-23 05:31:58
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: cfblk58
// Source Path: sampleModel71194_pp_7_1_sub/Subsystem/cfblk58
// Hierarchy Level: 1
// Model version: 1.1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module cfblk58
          (clk,
           reset,
           enb,
           emi_236,
           Action_Port,
           emi_237);


  input   clk;
  input   reset;
  input   enb;
  input   [7:0] emi_236;  // uint8
  input   Action_Port;
  output  [7:0] emi_237;  // uint8


  wire [7:0] cfblk58_out1;  // uint8
  wire [7:0] cfblk58_out1_bypass;  // uint8
  reg [7:0] cfblk58_out1_last_value;  // uint8


  assign cfblk58_out1 = (emi_236 > 8'b00000000 ? 8'b00000001 :
              8'b00000000);



  always @(posedge clk or posedge reset)
    begin : emi_237_bypass_process
      if (reset == 1'b1) begin
        cfblk58_out1_last_value <= 8'b00000000;
      end
      else begin
        if (enb) begin
          cfblk58_out1_last_value <= cfblk58_out1_bypass;
        end
      end
    end



  assign cfblk58_out1_bypass = (Action_Port == 1'b0 ? cfblk58_out1_last_value :
              cfblk58_out1);



  assign emi_237 = cfblk58_out1_bypass;

endmodule  // cfblk58

