// -------------------------------------------------------------
// 
// File Name: E:\zgl\gen_6\slemi\emi_results\2024-05-23-07-46-43\SampleModel61753\Verilog_hdlsrc\sampleModel61753_pp_45_1_sub\cfblk9.v
// Created: 2024-05-23 08:17:51
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: cfblk9
// Source Path: sampleModel61753_pp_45_1_sub/Subsystem/cfblk9
// Hierarchy Level: 1
// Model version: 1.1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module cfblk9
          (clk,
           reset,
           enb,
           emi_317,
           Action_Port,
           emi_318,
           emi_319);


  input   clk;
  input   reset;
  input   enb;
  input   [7:0] emi_317;  // uint8
  input   Action_Port;
  output  [7:0] emi_318;  // uint8
  output  [7:0] emi_319;  // uint8


  wire [7:0] cfblk9_out1;  // uint8
  wire [7:0] cfblk9_out2;  // uint8
  wire [7:0] cfblk9_out1_bypass;  // uint8
  reg [7:0] cfblk9_out1_last_value;  // uint8
  wire [7:0] cfblk9_out2_bypass;  // uint8
  reg [7:0] cfblk9_out2_last_value;  // uint8


  assign cfblk9_out1 = emi_317;
  assign cfblk9_out2 = 8'b00000000;



  always @(posedge clk or posedge reset)
    begin : emi_318_bypass_process
      if (reset == 1'b1) begin
        cfblk9_out1_last_value <= 8'b00000000;
      end
      else begin
        if (enb) begin
          cfblk9_out1_last_value <= cfblk9_out1_bypass;
        end
      end
    end



  assign cfblk9_out1_bypass = (Action_Port == 1'b0 ? cfblk9_out1_last_value :
              cfblk9_out1);



  assign emi_318 = cfblk9_out1_bypass;

  always @(posedge clk or posedge reset)
    begin : emi_319_bypass_process
      if (reset == 1'b1) begin
        cfblk9_out2_last_value <= 8'b00000000;
      end
      else begin
        if (enb) begin
          cfblk9_out2_last_value <= cfblk9_out2_bypass;
        end
      end
    end



  assign cfblk9_out2_bypass = (Action_Port == 1'b0 ? cfblk9_out2_last_value :
              cfblk9_out2);



  assign emi_319 = cfblk9_out2_bypass;

endmodule  // cfblk9

